### ISSUE TITLE
Get test coverage up

### ISSUE THREAD

**Issue by amaxwellblair** [amaxwellblair/the_pivot#98]
Delete existing code that doesn't need to be tested
Test code that is being actively used

**Comment by ksk5280** [comment]
File    % covered   Lines   Relevant Lines  Lines covered   Lines missed    Avg. Hits / Line
app/controllers/admin/base_controller.rb    0.0 %   2   2   0   2   0.0
app/controllers/admin/dashboard_controller.rb   0.0 %   5   5   0   5   0.0
app/controllers/admin/orders_controller.rb  0.0 %   19  19  0   19  0.0
app/controllers/weather_controller.rb   0.0 %   15  15  0   15  0.0
app/models/weather.rb   0.0 %   7   7   0   7   0.0
app/helpers/application_helper.rb   62.5 %  17  8   5   3   14.9
app/controllers/orders_controller.rb    80.0 %  38  25  20  5   1.3
app/services/permission.rb  81.69 % 103 71  58  13  72.0
app/controllers/stores_controller.rb    85.37 % 67  41  35  6   1.1
app/models/item.rb  85.71 % 36  21  18  3   1.5
app/controllers/stores/items_controller.rb  89.19 % 60  37  33  4   1.9
app/models/category.rb  90.0 %  16  10  9   1   14.1
app/controllers/application_controller.rb   92.59 % 49  27  25  2   99.0
app/controllers/users_controller.rb 95.92 % 79  49  47  2   4.9
